backend = "glx";
vsync = true;

blur-method = "dual_kawase";
blur-strength = 6;

shadow = true;

shadow-radius = 35;
shadow-offset-x = -35;
shadow-offset-y = -35;
shadow-opacity = 0.8;

# menu        = { shadow = false; };
dropdown_menu = { shadow = false; };
popup_menu    = { shadow = false; };
utility       = { shadow = false; };
