backend = "glx";
vsync = true;

# Blur
blur-method = "dual_kawase";
blur-strength = 5;
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'rofi'",
];

# Shadows
shadow = true;
shadow-radius = 14;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.35;

# menu        = { shadow = false; };
dropdown_menu = { shadow = false; };
popup_menu    = { shadow = false; };
utility       = { shadow = false; };

# Transparancy
inactive-opacity = 0.80;
active-opacity = 0.90;
frame-opacity = 0.90;

# Smooth animations
fading = true;
fade-in-step = 0.06;
fade-out-step = 0.06;

# Stability
use-damage = true;
