include theme.conf
#include ~/.cache/wal/colors-kitty.conf
#font_family Hack Nerd Font
#font_family BlexMono Nerd Font

# Font
font_family PlemolJP Console NF
font_size 16
bold_font        auto
italic_font      auto
bold_italic_font auto

# Window padding
window_padding_width 4

background_opacity 0.8
background_blur 7

# Shell_integration no-cursor
cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.05
cursor_shape block
cursor_blink true
cursor_blink_interval 0
set fish_cursor_default block   

enable_audio_bell no

scrollback_lines 10000

# Clipboard
copy_on_select yes
scrollback_pager nvim -c "set clipboard+=unnamedplus" -c "nnoremap q :qa!<CR>" -c "set nomodifiable" -






















# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
